<a href="https://colab.research.google.com/github/AI-KPI/DLBookNotes/blob/main/2.1 Scalars%2C Vectors%2C Matrices and Tensors/2_1_Scalars_Vectors_Matrices_and_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
#@title  {display-mode: "form"}
%%html
<style>
.pquote {
  text-align: left;
  margin: 40px 0 40px auto;
  width: 70%;
  font-size: 1.5em;
  font-style: italic;
  display: block;
  line-height: 1.3em;
  color: #5a75a7;
  font-weight: 600;
  border-left: 5px solid rgba(90, 117, 167, .1);
  padding-left: 6px;
}
.notes {
  font-style: italic;
  display: block;
  margin: 40px 10%;
}
img + em {
  text-align: center;
  display: block;
  color: gray;
  font-size: 0.9em;
  font-weight: 600;
}
</style>

$$
\newcommand\bs[1]{\boldsymbol{#1}}
$$

<span class='notes'>
    Дана стаття є частиною 2го розділу книги про лінійну алгебру з [Deep Learning Book] (http://www.deeplearningbook.org/) Гудфеллоу, І., Бенджо, Ю. та Курвіля, А. ( 2016). Вона спрямована на надання асоціаций / малюнків / коду Пайтона з математичних теорій і побудована як моє розуміння цих понять. Ви можете перевірити навчальний план у [вступній публікації] (https://hadrienj.github.io/posts/Deep-Learning-Book-Series-Introduction/).
</span>

# Вступ

Це перша публікація / блокнот із серії, що слідує навчальній програмі [глави про лінійну алгебру з Посібника про глибинне навчання] (http://www.deeplearningbook.org/contents/linear_algebra.html) від Goodfellow et al .. - це сукупність думок / деталей / розробок / прикладів, які я зробив, читаючи цей розділ. Він розроблений, щоб допомогти вам вивчити вступ до лінійної алгебри. Детальніше про цю серію та навчальну програму дивись у [вступній публікації] (https://hadrienj.github.io/posts/Deep-Learning-Book-Series-Introduction/).

Цей перший розділ досить легкий і стосується основних елементів, що використовуються в лінійній алгебрі, та їх визначень. Він також вводить важливі функції в Python / Numpy, якими ми будемо користуватися протягом усієї серії. Це пояснить, як створювати та використовувати вектори та матриці на прикладах.

# 2.1 Скаляри, вектори, матриці та тензори

Почнемо з деяких основних визначень:

<img src="https://github.com/AI-KPI/DLBookNotes/blob/main/2.1%20Scalars%2C%20Vectors%2C%20Matrices%20and%20Tensors/images/scalar-vector-matrix-tensor.png?raw=1" width="400" alt="An example of a scalar, a vector, a matrix and a tensor" title="Difference between a scalar, a vector, a matrix and a tensor">
<em>Різниця між скаляром, вектором, матрицею і тензором</em>

- Скаляр - це одне число
- Вектор - це масив чисел.

$$
\bs{x} =\begin{bmatrix}
    x_1 \\\\
    x_2 \\\\
    \cdots \\\\
    x_n
\end{bmatrix}
$$

- Матриця - це двовимірний масив

$$
\bs{A}=
\begin{bmatrix}
    A_{1,1} & A_{1,2} & \cdots & A_{1,n} \\\\
    A_{2,1} & A_{2,2} & \cdots & A_{2,n} \\\\
    \cdots & \cdots & \cdots & \cdots \\\\
    A_{m,1} & A_{m,2} & \cdots & A_{m,n}
\end{bmatrix}
$$

- Тензор - це $ n $ -вимірний масив з $ n> 2 $

Ми дотримуватимемось конвенцій, що використовуються в [Deep Learning Book](http://www.deeplearningbook.org/):

- скаляри пишуться малими літерами та курсивом. Наприклад: $ n $
- вектори пишуться малими літерами, курсивом та жирним шрифтом. Наприклад: $\bs{x}$
- матриці пишуться великими літерами, курсивом та жирним шрифтом. Наприклад: $\bs{X}$

### Приклад 1.

#### Створіть вектор за допомогою Python та Numpy

*Підказка щодо програмування*: На відміну від функції `matrix ()`, яка обов'язково створює $ 2 $-вимірні матриці, ви можете створити $ n $-вимірні масиви за допомогою функції `array ()`. Головною перевагою використання `matrix ()` є корисні методи (кон'юговане транспонування, обернення матриці, матричні операції ...). Ми будемо використовувати функцію ʻarray () `у цій серії.

Ми почнемо зі створення вектора. Це просто $ 1 $-вимірний масив:

In [3]:
x = np.array([1, 2, 3, 4])
x

array([1, 2, 3, 4])

### Приклад 2.

#### Створіть матрицю (3x2) із вкладеними дужками

Функція `array () `також може створювати $ 2 $-вимірні масиви з вкладеними дужками:

In [4]:
A = np.array([[1, 2], [3, 4], [5, 6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

### Розмірність масиву

Розмірність масиву (тобто його розміри) повідомляє вам кількість значень для кожного виміру. Для $ 2 $-вимірного масиву це дасть вам кількість рядків і кількість стовпців. Давайте знайдемо розмірність попереднього $ 2 $-вимірного масиву `A`. Оскільки `A` є масивом Numpy (він був створений за допомогою функції `array () `), ви можете отримати доступ до його розмірності за допомогою:

In [5]:
A.shape

(3, 2)

Ми бачимо, що $\bs{A}$ має 3 рядки та 2 стовпці.

Давайте перевіримо розмірність нашого першого вектора:

In [6]:
x.shape

(4,)

Як і очікувалось, $\bs{x}$ має лише один вимір(одновимірний). Число відповідає довжині масиву:

In [7]:
len(x)

4

# Транпонування

За допомогою транпонування ви можете перетворити вектор-рядок у вектор-стовпець і навпаки:

<img src="https://github.com/AI-KPI/DLBookNotes/blob/main/2.1%20Scalars%2C%20Vectors%2C%20Matrices%20and%20Tensors/images/vector-transposition.png?raw=1" alt="Transposition of a vector" title="Vector transposition" width="200">
<em>Транспонування вектораn</em>

Транспонування $\bs{A}^{\text{T}}$ матриці $\bs{A}$ відповідає дзеркальному відображенню по осям. Якщо матриця - це квадратна матриця (однакова кількість стовпців і рядків):

<img src="https://github.com/AI-KPI/DLBookNotes/blob/main/2.1%20Scalars%2C%20Vectors%2C%20Matrices%20and%20Tensors/images/square-matrix-transposition.png?raw=1" alt="Transposition of a square matrix" title="Square matrix transposition" width="300">
<em>Транспонування квадратної матриці</em>

Якщо матриця не квадратна, ідея однакова:

<img src="https://github.com/AI-KPI/DLBookNotes/blob/main/2.1%20Scalars%2C%20Vectors%2C%20Matrices%20and%20Tensors/images/non-squared-matrix-transposition.png?raw=1" alt="Transposition of a square matrix" title="Non square matrix transposition" width="300">
<em>Транспонування не квадратичної матриці</em>


Верхній індекс $^\text{T}$ використовується для транспонованих матриць.

$$
\bs{A}=
\begin{bmatrix}
    A_{1,1} & A_{1,2} \\\\
    A_{2,1} & A_{2,2} \\\\
    A_{3,1} & A_{3,2}
\end{bmatrix}
$$

$$
\bs{A}^{\text{T}}=
\begin{bmatrix}
    A_{1,1} & A_{2,1} & A_{3,1} \\\\
    A_{1,2} & A_{2,2} & A_{3,2}
\end{bmatrix}
$$

Форма ($m\times n$) інвертується і стає ($n\times m$).

<img src="https://github.com/AI-KPI/DLBookNotes/blob/main/2.1%20Scalars%2C%20Vectors%2C%20Matrices%20and%20Tensors/images/dimensions-transposition-matrix.png?raw=1" alt="Dimensions of matrix transposition" title="Dimensions of matrix transposition" width="300">
<em>Розмірність транспонованої мариці</em>

### Приклад 3.

#### Створіть матрицю A і транспонуйте її

In [8]:
A = np.array([[1, 2], [3, 4], [5, 6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [9]:
A_t = A.T
A_t

array([[1, 3, 5],
       [2, 4, 6]])

Ми можемо перевірити розмірність матриці:

In [10]:
A.shape

(3, 2)

In [11]:
A_t.shape

(2, 3)

Ми бачимо, що кількість стовпців стає кількістю рядків після транспонування і навпаки.

# Додавання

<img src="https://github.com/AI-KPI/DLBookNotes/blob/main/2.1%20Scalars%2C%20Vectors%2C%20Matrices%20and%20Tensors/images/matrix-addition.png?raw=1" alt="Addition of two matrices" title="Addition of two matrices" width="300">
<em>Додавання двох матриць</em>

Матриці можна додавати, якщо вони мають однакову розмірність:

$$\bs{A} + \bs{B} = \bs{C}$$

Кожен елемент $\bs{A}$ додається до відповідного елементу $\bs{B}$:

$$\bs{A}_{i,j} + \bs{B}_{i,j} = \bs{C}_{i,j}$$

$i$ - індекс рядка та $j$ - індекс стовпця.

$$
\begin{bmatrix}
    A_{1,1} & A_{1,2} \\\\
    A_{2,1} & A_{2,2} \\\\
    A_{3,1} & A_{3,2}
\end{bmatrix}+
\begin{bmatrix}
    B_{1,1} & B_{1,2} \\\\
    B_{2,1} & B_{2,2} \\\\
    B_{3,1} & B_{3,2}
\end{bmatrix}=
\begin{bmatrix}
    A_{1,1} + B_{1,1} & A_{1,2} + B_{1,2} \\\\
    A_{2,1} + B_{2,1} & A_{2,2} + B_{2,2} \\\\
    A_{3,1} + B_{3,1} & A_{3,2} + B_{3,2}
\end{bmatrix}
$$

Розмірність $\bs{A}$, $\bs{B}$ і $\bs{C}$ однакові. Перевіримо це на прикладі:

### Приклад 4.

#### Створіть дві матриці A і B і додайте їх

За допомогою Numpy ви можете додавати матриці так само, як і вектори або скаляри.

In [12]:
A = np.array([[1, 2], [3, 4], [5, 6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [13]:
B = np.array([[2, 5], [7, 4], [4, 3]])
B

array([[2, 5],
       [7, 4],
       [4, 3]])

In [14]:
# Додавання A і B
C = A + B
C

array([[ 3,  7],
       [10,  8],
       [ 9,  9]])

Також можна додати скаляр до матриці. Це означає додавання цього скаляра до кожного елементу матриці.

$$
\alpha+ \begin{bmatrix}
    A_{1,1} & A_{1,2} \\\\
    A_{2,1} & A_{2,2} \\\\
    A_{3,1} & A_{3,2}
\end{bmatrix}=
\begin{bmatrix}
    \alpha + A_{1,1} & \alpha + A_{1,2} \\\\
    \alpha + A_{2,1} & \alpha + A_{2,2} \\\\
    \alpha + A_{3,1} & \alpha + A_{3,2}
\end{bmatrix}
$$

### Приклад 5.

#### Додавання скаляру до матриці

In [15]:
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [16]:
# Приклад: Додати 4 до матриці A
C = A+4
C

array([[ 5,  6],
       [ 7,  8],
       [ 9, 10]])

# Розширення

Numpy може обробляти операції з масивами різної розмірності. Менший масив буде розширений відповідно до розмірності більшого. Перевага полягає в тому, що це робиться в `C` під капотом (як і будь-які векторні операції в Numpy). Власне, ми використовували розширення у прикладі 5. Скаляр був перетворений у масив тієї ж форми, що і $\bs{A}$.

Ось ще один загальний приклад:

$$
\begin{bmatrix}
    A_{1,1} & A_{1,2} \\\\
    A_{2,1} & A_{2,2} \\\\
    A_{3,1} & A_{3,2}
\end{bmatrix}+
\begin{bmatrix}
    B_{1,1} \\\\
    B_{2,1} \\\\
    B_{3,1}
\end{bmatrix}
$$

еквівалентно до

$$
\begin{bmatrix}
    A_{1,1} & A_{1,2} \\\\
    A_{2,1} & A_{2,2} \\\\
    A_{3,1} & A_{3,2}
\end{bmatrix}+
\begin{bmatrix}
    B_{1,1} & B_{1,1} \\\\
    B_{2,1} & B_{2,1} \\\\
    B_{3,1} & B_{3,1}
\end{bmatrix}=
\begin{bmatrix}
    A_{1,1} + B_{1,1} & A_{1,2} + B_{1,1} \\\\
    A_{2,1} + B_{2,1} & A_{2,2} + B_{2,1} \\\\
    A_{3,1} + B_{3,1} & A_{3,2} + B_{3,1}
\end{bmatrix}
$$

де матриця ($3 \times 1 $) перетворюється в потрібну форму ($ 3 \times 2 $) шляхом копіювання першого стовпця. Numpy зробить це автоматично, якщо розмірності можуть збігатися.

### Приклад 6.

#### Додайте дві матриці різної форми

In [17]:
A = np.array([[1, 2], [3, 4], [5, 6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [18]:
B = np.array([[2], [4], [6]])
B

array([[2],
       [4],
       [6]])

In [19]:
# Розширення
C=A+B
C

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

Ви можете знайти основні операції з матрицями, описані простою мовою [тут](https://www.mathsisfun.com/algebra/matrix-introduction.html).

<span class='notes'>
    Не соромтеся писати мені на електронну пошту чи коментарі. Програму цієї серії можна знайти [у вступномі пості](https://hadrienj.github.io/posts/Deep-Learning-Book-Series-Introduction/). Всі блокноти можна знайти на [Github](https://github.com/hadrienj/deepLearningBook-Notes).
</span>

# Список використаної літератури

- [Скаляри, вектори, матриці та тензори](https://github.com/hadrienj/deepLearningBook-Notes/tree/master/2.1%20Scalars%2C%20Vectors%2C%20Matrices%20and%20Tensors)

Переклад: Панасюк Олександр, студент ІО-02мп, 2020 рік